# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mydb
  pool: 5
  timeout: 5000
  username: postgres
  password: password
  min_messages: WARNING

test:
  host: localhost
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: mydb
  pool: 5
  timeout: 5000
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  min_messages: WARNING
